cabal-version: 3.0
name:          TypesAndIO
version:       0.1.0.0
maintainer:    daniel.kroeni@fhnw.ch
author:        Daniel Kröni
build-type:    Simple

executable wttr
    main-is:          Main.hs
    default-language: Haskell2010
    ghc-options:      -Wall
    build-depends:
        base >=4.17 && <5,
        http-client-tls,
        http-client,
        bytestring,
        text

executable hcp
    main-is: hcp1.hs
    default-language: Haskell2010
    ghc-options: -Wall
    build-depends:
        base >=4.17 && <5,

executable hcp2
    main-is: hcp2.hs
    default-language: Haskell2010
    ghc-options: -Wall
    build-depends:
        base >=4.17 && <5,